version: '3.8'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  airflow:
    image: apache/airflow:latest
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - kafka
      - cassandra
      - mongodb
